import React from 'react'
import { Separator } from '@/components/ui/separator'
import { Heading } from '@/components/common/heading'
import { DataTable } from '@/components/ui/data-table/data-table'
import { api } from '@/utils/api'
import { Loading } from '@/components/common/loading'
import { columns } from "@/components/page-component/users/columns"
import { user } from '@/lib/validators'

const Users = () => {
    // const { data, isLoading, isError, error } = api.user.getAll.useQuery()

    // if (isLoading) return <Loading />

    // if (isError) return <div>Error: {error.message}</div>

    const users = [{
        "id": 1,
        "first_name": "Jacquelynn",
        "last_name": "Callingham",
        "email": "jcallingham0@canalblog.com",
        "gender": "Female"
    }, {
        "id": 2,
        "first_name": "Hube",
        "last_name": "Gerren",
        "email": "hgerren1@sakura.ne.jp",
        "gender": "Male"
    }, {
        "id": 3,
        "first_name": "Neddie",
        "last_name": "Jeenes",
        "email": "njeenes2@salon.com",
        "gender": "Male"
    }, {
        "id": 4,
        "first_name": "Herbert",
        "last_name": "Weeden",
        "email": "hweeden3@amazon.co.jp",
        "gender": "Male"
    }, {
        "id": 5,
        "first_name": "Matt",
        "last_name": "Benkin",
        "email": "mbenkin4@fda.gov",
        "gender": "Polygender"
    }, {
        "id": 6,
        "first_name": "Adolpho",
        "last_name": "Khomishin",
        "email": "akhomishin5@php.net",
        "gender": "Male"
    }, {
        "id": 7,
        "first_name": "Helga",
        "last_name": "Churn",
        "email": "hchurn6@skyrock.com",
        "gender": "Polygender"
    }, {
        "id": 8,
        "first_name": "Bobbette",
        "last_name": "Livoir",
        "email": "blivoir7@liveinternet.ru",
        "gender": "Female"
    }, {
        "id": 9,
        "first_name": "Raviv",
        "last_name": "Lombardo",
        "email": "rlombardo8@wsj.com",
        "gender": "Male"
    }, {
        "id": 10,
        "first_name": "Farra",
        "last_name": "Oxterby",
        "email": "foxterby9@lycos.com",
        "gender": "Female"
    }, {
        "id": 11,
        "first_name": "Mitchael",
        "last_name": "Leach",
        "email": "mleacha@miibeian.gov.cn",
        "gender": "Male"
    }, {
        "id": 12,
        "first_name": "Gran",
        "last_name": "Winward",
        "email": "gwinwardb@sitemeter.com",
        "gender": "Male"
    }, {
        "id": 13,
        "first_name": "Raymund",
        "last_name": "Trencher",
        "email": "rtrencherc@icq.com",
        "gender": "Male"
    }, {
        "id": 14,
        "first_name": "Ambros",
        "last_name": "Kivlin",
        "email": "akivlind@skype.com",
        "gender": "Male"
    }, {
        "id": 15,
        "first_name": "Karina",
        "last_name": "Maven",
        "email": "kmavene@weather.com",
        "gender": "Polygender"
    }, {
        "id": 16,
        "first_name": "Ferguson",
        "last_name": "Filde",
        "email": "ffildef@php.net",
        "gender": "Male"
    }, {
        "id": 17,
        "first_name": "Cyrille",
        "last_name": "Babcock",
        "email": "cbabcockg@hibu.com",
        "gender": "Male"
    }, {
        "id": 18,
        "first_name": "Lawrence",
        "last_name": "McIlvaney",
        "email": "lmcilvaneyh@uol.com.br",
        "gender": "Male"
    }, {
        "id": 19,
        "first_name": "Nataniel",
        "last_name": "Jinks",
        "email": "njinksi@arstechnica.com",
        "gender": "Male"
    }, {
        "id": 20,
        "first_name": "Gearalt",
        "last_name": "Heersema",
        "email": "gheersemaj@mlb.com",
        "gender": "Male"
    }, {
        "id": 21,
        "first_name": "Gisella",
        "last_name": "Stratford",
        "email": "gstratfordk@homestead.com",
        "gender": "Female"
    }, {
        "id": 22,
        "first_name": "Arabella",
        "last_name": "Redmore",
        "email": "aredmorel@miibeian.gov.cn",
        "gender": "Female"
    }, {
        "id": 23,
        "first_name": "Cleve",
        "last_name": "Paunsford",
        "email": "cpaunsfordm@arstechnica.com",
        "gender": "Male"
    }, {
        "id": 24,
        "first_name": "Lemmie",
        "last_name": "Bras",
        "email": "lbrasn@webeden.co.uk",
        "gender": "Genderqueer"
    }, {
        "id": 25,
        "first_name": "Simone",
        "last_name": "Callery",
        "email": "scalleryo@ebay.co.uk",
        "gender": "Female"
    }, {
        "id": 26,
        "first_name": "Elvira",
        "last_name": "Dickey",
        "email": "edickeyp@deliciousdays.com",
        "gender": "Female"
    }, {
        "id": 27,
        "first_name": "Christa",
        "last_name": "Underhill",
        "email": "cunderhillq@nytimes.com",
        "gender": "Female"
    }, {
        "id": 28,
        "first_name": "Barret",
        "last_name": "Verbeek",
        "email": "bverbeekr@google.de",
        "gender": "Male"
    }, {
        "id": 29,
        "first_name": "Barbey",
        "last_name": "Grellier",
        "email": "bgrelliers@reuters.com",
        "gender": "Female"
    }, {
        "id": 30,
        "first_name": "Salomon",
        "last_name": "Harrop",
        "email": "sharropt@gizmodo.com",
        "gender": "Male"
    }, {
        "id": 31,
        "first_name": "Dorrie",
        "last_name": "Kedward",
        "email": "dkedwardu@prlog.org",
        "gender": "Female"
    }, {
        "id": 32,
        "first_name": "Kimbell",
        "last_name": "Petruk",
        "email": "kpetrukv@miitbeian.gov.cn",
        "gender": "Male"
    }, {
        "id": 33,
        "first_name": "Adeline",
        "last_name": "Dreier",
        "email": "adreierw@bloglines.com",
        "gender": "Female"
    }, {
        "id": 34,
        "first_name": "Darrel",
        "last_name": "Woofinden",
        "email": "dwoofindenx@indiatimes.com",
        "gender": "Male"
    }, {
        "id": 35,
        "first_name": "Noami",
        "last_name": "Lusher",
        "email": "nlushery@ted.com",
        "gender": "Female"
    }, {
        "id": 36,
        "first_name": "Clio",
        "last_name": "Pantridge",
        "email": "cpantridgez@nps.gov",
        "gender": "Agender"
    }, {
        "id": 37,
        "first_name": "Karry",
        "last_name": "Heilds",
        "email": "kheilds10@indiatimes.com",
        "gender": "Polygender"
    }, {
        "id": 38,
        "first_name": "Winny",
        "last_name": "Phayre",
        "email": "wphayre11@nhs.uk",
        "gender": "Female"
    }, {
        "id": 39,
        "first_name": "Nil",
        "last_name": "Whiten",
        "email": "nwhiten12@go.com",
        "gender": "Male"
    }, {
        "id": 40,
        "first_name": "Felic",
        "last_name": "Beedle",
        "email": "fbeedle13@cyberchimps.com",
        "gender": "Male"
    }, {
        "id": 41,
        "first_name": "Aura",
        "last_name": "Clemmett",
        "email": "aclemmett14@youku.com",
        "gender": "Female"
    }, {
        "id": 42,
        "first_name": "Jodi",
        "last_name": "Bosley",
        "email": "jbosley15@washington.edu",
        "gender": "Female"
    }, {
        "id": 43,
        "first_name": "Kiley",
        "last_name": "McMillam",
        "email": "kmcmillam16@mayoclinic.com",
        "gender": "Female"
    }, {
        "id": 44,
        "first_name": "Lilian",
        "last_name": "Baptista",
        "email": "lbaptista17@who.int",
        "gender": "Genderqueer"
    }, {
        "id": 45,
        "first_name": "Dilly",
        "last_name": "Halfacre",
        "email": "dhalfacre18@merriam-webster.com",
        "gender": "Male"
    }, {
        "id": 46,
        "first_name": "Stacey",
        "last_name": "Bushen",
        "email": "sbushen19@yelp.com",
        "gender": "Female"
    }, {
        "id": 47,
        "first_name": "Ripley",
        "last_name": "Alenichev",
        "email": "ralenichev1a@archive.org",
        "gender": "Male"
    }, {
        "id": 48,
        "first_name": "Toddy",
        "last_name": "Ovize",
        "email": "tovize1b@spiegel.de",
        "gender": "Male"
    }, {
        "id": 49,
        "first_name": "Cedric",
        "last_name": "Beeho",
        "email": "cbeeho1c@facebook.com",
        "gender": "Male"
    }, {
        "id": 50,
        "first_name": "Lyndsay",
        "last_name": "Verrick",
        "email": "lverrick1d@ycombinator.com",
        "gender": "Genderqueer"
    }, {
        "id": 51,
        "first_name": "Dyanne",
        "last_name": "Silverthorn",
        "email": "dsilverthorn1e@wufoo.com",
        "gender": "Female"
    }, {
        "id": 52,
        "first_name": "Allard",
        "last_name": "Sutheran",
        "email": "asutheran1f@washington.edu",
        "gender": "Male"
    }, {
        "id": 53,
        "first_name": "Davidde",
        "last_name": "Cheson",
        "email": "dcheson1g@techcrunch.com",
        "gender": "Male"
    }, {
        "id": 54,
        "first_name": "Lily",
        "last_name": "Chichgar",
        "email": "lchichgar1h@reuters.com",
        "gender": "Female"
    }, {
        "id": 55,
        "first_name": "Phylis",
        "last_name": "Blamires",
        "email": "pblamires1i@tripod.com",
        "gender": "Female"
    }, {
        "id": 56,
        "first_name": "Ives",
        "last_name": "Slessar",
        "email": "islessar1j@oakley.com",
        "gender": "Male"
    }, {
        "id": 57,
        "first_name": "Kelvin",
        "last_name": "Bainbrigge",
        "email": "kbainbrigge1k@mapquest.com",
        "gender": "Male"
    }, {
        "id": 58,
        "first_name": "Ritchie",
        "last_name": "Tuxill",
        "email": "rtuxill1l@plala.or.jp",
        "gender": "Male"
    }, {
        "id": 59,
        "first_name": "Ardene",
        "last_name": "Hallut",
        "email": "ahallut1m@ebay.com",
        "gender": "Female"
    }, {
        "id": 60,
        "first_name": "Leena",
        "last_name": "Ferencowicz",
        "email": "lferencowicz1n@1und1.de",
        "gender": "Genderfluid"
    }, {
        "id": 61,
        "first_name": "Theadora",
        "last_name": "Salmoni",
        "email": "tsalmoni1o@cbsnews.com",
        "gender": "Polygender"
    }, {
        "id": 62,
        "first_name": "Melissa",
        "last_name": "Laugherane",
        "email": "mlaugherane1p@shareasale.com",
        "gender": "Female"
    }, {
        "id": 63,
        "first_name": "Sonnnie",
        "last_name": "Sammut",
        "email": "ssammut1q@google.es",
        "gender": "Female"
    }, {
        "id": 64,
        "first_name": "Berti",
        "last_name": "Scrivens",
        "email": "bscrivens1r@census.gov",
        "gender": "Agender"
    }, {
        "id": 65,
        "first_name": "Alessandra",
        "last_name": "Paxton",
        "email": "apaxton1s@apple.com",
        "gender": "Female"
    }, {
        "id": 66,
        "first_name": "Consuelo",
        "last_name": "Vickerman",
        "email": "cvickerman1t@webeden.co.uk",
        "gender": "Female"
    }, {
        "id": 67,
        "first_name": "Shaylyn",
        "last_name": "Boulds",
        "email": "sboulds1u@wikispaces.com",
        "gender": "Female"
    }, {
        "id": 68,
        "first_name": "Maurie",
        "last_name": "Sapshed",
        "email": "msapshed1v@163.com",
        "gender": "Non-binary"
    }, {
        "id": 69,
        "first_name": "Sigrid",
        "last_name": "Wasiel",
        "email": "swasiel1w@blinklist.com",
        "gender": "Female"
    }, {
        "id": 70,
        "first_name": "Obadiah",
        "last_name": "Parminter",
        "email": "oparminter1x@samsung.com",
        "gender": "Agender"
    }, {
        "id": 71,
        "first_name": "Nara",
        "last_name": "Sanbrook",
        "email": "nsanbrook1y@blinklist.com",
        "gender": "Female"
    }, {
        "id": 72,
        "first_name": "Joannes",
        "last_name": "Jorgesen",
        "email": "jjorgesen1z@weebly.com",
        "gender": "Female"
    }, {
        "id": 73,
        "first_name": "Charlotte",
        "last_name": "Khomishin",
        "email": "ckhomishin20@jugem.jp",
        "gender": "Female"
    }, {
        "id": 74,
        "first_name": "Louise",
        "last_name": "Riguard",
        "email": "lriguard21@pcworld.com",
        "gender": "Female"
    }, {
        "id": 75,
        "first_name": "Cherish",
        "last_name": "Tailby",
        "email": "ctailby22@oaic.gov.au",
        "gender": "Non-binary"
    }, {
        "id": 76,
        "first_name": "Kriste",
        "last_name": "Levy",
        "email": "klevy23@yolasite.com",
        "gender": "Female"
    }, {
        "id": 77,
        "first_name": "Kelley",
        "last_name": "Ginner",
        "email": "kginner24@reverbnation.com",
        "gender": "Male"
    }, {
        "id": 78,
        "first_name": "Christy",
        "last_name": "Hasard",
        "email": "chasard25@prweb.com",
        "gender": "Polygender"
    }, {
        "id": 79,
        "first_name": "Anjela",
        "last_name": "Trahar",
        "email": "atrahar26@pagesperso-orange.fr",
        "gender": "Female"
    }, {
        "id": 80,
        "first_name": "Anny",
        "last_name": "Noke",
        "email": "anoke27@engadget.com",
        "gender": "Female"
    }, {
        "id": 81,
        "first_name": "Kari",
        "last_name": "Boother",
        "email": "kboother28@epa.gov",
        "gender": "Female"
    }, {
        "id": 82,
        "first_name": "Ado",
        "last_name": "Kellough",
        "email": "akellough29@sakura.ne.jp",
        "gender": "Male"
    }, {
        "id": 83,
        "first_name": "Kizzie",
        "last_name": "Reiglar",
        "email": "kreiglar2a@virginia.edu",
        "gender": "Female"
    }, {
        "id": 84,
        "first_name": "Tobe",
        "last_name": "Quiddington",
        "email": "tquiddington2b@1688.com",
        "gender": "Female"
    }, {
        "id": 85,
        "first_name": "Shandy",
        "last_name": "Pachmann",
        "email": "spachmann2c@umich.edu",
        "gender": "Female"
    }, {
        "id": 86,
        "first_name": "Melosa",
        "last_name": "Scotting",
        "email": "mscotting2d@guardian.co.uk",
        "gender": "Female"
    }, {
        "id": 87,
        "first_name": "Chauncey",
        "last_name": "Oates",
        "email": "coates2e@uiuc.edu",
        "gender": "Male"
    }, {
        "id": 88,
        "first_name": "Alysia",
        "last_name": "Bussey",
        "email": "abussey2f@ebay.co.uk",
        "gender": "Female"
    }, {
        "id": 89,
        "first_name": "Betsy",
        "last_name": "Mallindine",
        "email": "bmallindine2g@mozilla.org",
        "gender": "Female"
    }, {
        "id": 90,
        "first_name": "Gwyn",
        "last_name": "Minihane",
        "email": "gminihane2h@jimdo.com",
        "gender": "Female"
    }, {
        "id": 91,
        "first_name": "Raimund",
        "last_name": "Arnatt",
        "email": "rarnatt2i@dailymotion.com",
        "gender": "Male"
    }, {
        "id": 92,
        "first_name": "Stafani",
        "last_name": "Heers",
        "email": "sheers2j@answers.com",
        "gender": "Non-binary"
    }, {
        "id": 93,
        "first_name": "Bennie",
        "last_name": "McNiff",
        "email": "bmcniff2k@geocities.jp",
        "gender": "Male"
    }, {
        "id": 94,
        "first_name": "Manfred",
        "last_name": "Runnicles",
        "email": "mrunnicles2l@europa.eu",
        "gender": "Male"
    }, {
        "id": 95,
        "first_name": "Barris",
        "last_name": "Leyre",
        "email": "bleyre2m@wordpress.org",
        "gender": "Male"
    }, {
        "id": 96,
        "first_name": "Ulrikaumeko",
        "last_name": "Zeale",
        "email": "uzeale2n@wsj.com",
        "gender": "Female"
    }, {
        "id": 97,
        "first_name": "Ardella",
        "last_name": "Bonhomme",
        "email": "abonhomme2o@auda.org.au",
        "gender": "Female"
    }, {
        "id": 98,
        "first_name": "Neil",
        "last_name": "Coverly",
        "email": "ncoverly2p@vistaprint.com",
        "gender": "Male"
    }, {
        "id": 99,
        "first_name": "Angelique",
        "last_name": "Currer",
        "email": "acurrer2q@upenn.edu",
        "gender": "Female"
    }, {
        "id": 100,
        "first_name": "Nerita",
        "last_name": "Dark",
        "email": "ndark2r@census.gov",
        "gender": "Female"
    }]
    return (
        <div className='flex h-full flex-col space-y-4 p-4 pt-6 md:p-8'>
            <Heading />
            <Separator />
            <div className='flex-1 rounded'>
                <DataTable columns={columns} data={users} />
            </div>
        </div>
    )
}

export default Users